### ISSUE TITLE
Lag oversikt over hvilke bilder som kan gjenbrukes der vi ikke har bilde

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/natursystem-ubehandlet#1]
Se dummy eksempel i https://github.com/Artsdatabanken/nin-data/blob/master/Natur_i_Norge/Landskap/bilder_som_gjenbrukes.csv

Strukturer på en måte som gjør det enklest mulig å fylle inn.

**Comment by runningbones** [comment]
Ser på det i kveld! Tror vi får fylt på bra.

**Comment by runningbones** [comment]
Bruk bilde på | Bruk bilde fra
-- | --
KLG-JP-2 | LA-I-A-4
KLG-JP | LA-I-A-4
KLG-VE | LA-I-A-12
KLG-VE-4 | LA-I-A-12
KLG-BP-2 | LA-I-S-12
KLG-BP | LA-I-S-12
KLG-AI | LA-K-S-31
KLG-IYK | LA-K-S-57
KLG-IYK-4 | LA-K-S-57
KLG-IP-3 | LA-I-D-27
KLG-IP | LA-I-D-27
KLG-VP | LA-I-D-3
KLG-VP-2 | LA-I-D-3

**Comment by runningbones** [comment]
kommer i tillegg noen nye bilder.

**Comment by runningbones** [comment]
flere bilder ligger her: https://filesender.uninett.no/?s=download&token=82422e87-4420-4e38-9eff-7736bb8ad211

struktur filnavn: begynner med kode med "-" somskilletegn.

**Comment by bjornreppen** [comment]
Mapping av filnavn i https://github.com/Artsdatabanken/kverna/pull/511  (burde også flyttes til lastejobb-bilder)

Bildekonvertering i https://github.com/Artsdatabanken/lastejobb-bilder/commit/43d554607a7f7496585723624f740a5b79ba2cc5

Alle bilder skal være ute med unntak av PNG-filene som trenger en oppdatering av datagrunnlag og innsynsklient.

**Comment by bjornreppen** [comment]
Beklager offentlig til alle som har bidratt med bilder at vi ikke har hatt kapasitet til å behandle dem på den måten de fortjener.. det kommer.

**Comment by bjornreppen** [comment]
Fixed!
