### ISSUE TITLE
LA-MP/natur-/kulturlandskap - endre begrep(vokabular)

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/natursystem-ubehandlet#3]
'{
"tittel": {
"nb": "Arealbrukspreg"
},
"skjul": true,
"type": "flagg",
"farge": "hsl(56, 75%, 63%)",
"overordnet": [
{
"kode": "NN-LA",
"tittel": {
"nb": "Landskap"
},
"url": "Natur_i_Norge/Landskap",
"nivå": "Landskap"
},
{
"kode": "NN",
"tittel": {
"nb": "Natur i Norge",
"la": "Naturae Norvegia"
},
"url": "Natur_i_Norge",
"nivå": "Natur i Norge"
},
{
"kode": "~",
"tittel": {
"nb": "Katalog",
"la": "Katalog"
},
"url": "Katalog"
}
],
"barn": [
{
"tittel": {
"nb": "Arealbrukspreget landskapstype"
},
"kode": "NN-LA-MP-KL",
"url": "Natur_i_Norge/Landskap/Arealbrukspreg/Arealbrukspreget_landskapstype",
"sortering": 2,
"farge": "#fc8d59"
}
],
"url": "Natur_i_Norge/Landskap/Arealbrukspreg",
"nivå": "Landskap",
"undernivå": "Landskap",
"kode": "NN-LA-MP",
"foto": {}
}

**Comment by runningbones** [comment]
Forsøk på manipulere JSON

**Comment by bjornreppen** [comment]
Skal ta den inn!  Du må bare manipulere rett i filene også... ikke noe stress.. det verste som som regel skjer er at kverna stopper midtveis.. og da fikser jeg opp fila og starter på nytt.

**Comment by bjornreppen** [comment]
Ser også at de 2 filene sikkert burde vært slått sammen i CSV-fila.. senere. :D

**Comment by bjornreppen** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/281359/55232204-0ef95680-5225-11e9-8611-3239efc0f0f2.png)

**Comment by runningbones** [comment]
FInt om den flyttes ut av treet (ligger på på LA-toppnviå) KAn med fordel fjernes:)

SLiter ogsgå med å finne sted/fil for regigering av bekrivelse av la-mp.

**Comment by bjornreppen** [comment]
https://github.com/Artsdatabanken/nin-data/blob/master/Natur_i_Norge/Landskap/Typeinndeling/type.json

**Comment by bjornreppen** [comment]
Søk på hele ord i hele repoet fungerer forresten overraskende bra hvis du lurer på hvilken fil ting ligger i.  Og ja.. burde vært samlet i en fil.. men tid.
