### ISSUE TITLE
L4: Kartleggingsenheter?

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/natursystem-ubehandlet#6]
Det ligger tilsynelatende ingen kartleggingsenheter under L4 Helofytt-ferskvannssump
i https://github.com/Artsdatabanken/natursystem-ubehandlet/blob/master/kodeliste_v2b.json

Er dette en feil?  Har alle typer uten kartleggingsenheter på større målestokk bare falt ut?

**Comment by runningbones** [comment]
Finnes kun målestokktilpassede kartleggingsenheter for T og V. Noen har likevel kartlagt grunntyper i L4  med C (1:5000) kode, men er i realiteten grunntypene som er kartlagt. Nummeret bak C er grunntypenummer.
